DROP TABLE IF EXISTS notes;

CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,  
  note TEXT,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id_ date_created)
)